# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg_app', '0002_auto_20180522_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wish_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wish', to='log_reg_app.User')),
                ('wisher', models.ManyToManyField(related_name='wisher_wish', to='log_reg_app.User')),
            ],
        ),
    ]
